name: Build and deploy to gh-pages
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout  ✔
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm 📦
        with:
          run_install: false

      - name: Install Node.js ⚡️
        uses: actions/setup-node@v7
        with:
          cache: "pnpm"
          node-version: 24

      - name: Build 🔧
        run: |
          pnpm install
          pnpm build:docs

      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
